### ISSUE TITLE
Allow mods to expose tooltip information for their fluids

### ISSUE THREAD

**Issue by UpcraftLP** [FabLabsMC/FluidStacks#3]
I think mods should be able to expose tooltips for their fluids, so that GUIs can make use of that (for tanks, mainly).

The accepted workaround for this in Forge land would be to grab a bucket ItemStack for a given fluid, then get the tooltip from that. I think we can do better than that, and expose tooltips natively, if a GUI wishes to display them.

**Comment by Ueaj-Kerman** [comment]
so, add a toString to FluidVolume?

**Comment by Ueaj-Kerman** [comment]
toText*

**Comment by Ueaj-Kerman** [comment]
https://github.com/FabLabsMC/FluidApi/pull/4 done

**Comment by UpcraftLP** [comment]
No, not a `toText()` method on FluidVolume, but rather a method that provides a List of Text objects, for rendering tooltips. Also on the fluid itself, not on the volume holding it.

(Similar to `Item#appendTooltip()`)
